# Generated by Django 6.1.1 on 2026-10-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Abbreviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(max_length=40, unique=True, verbose_name="줄임말"),
                ),
                ("expansion", models.CharField(max_length=100, verbose_name="확장형")),
                (
                    "category",
                    models.CharField(blank=True, max_length=40, verbose_name="분류"),
                ),
                (
                    "ambiguous",
                    models.BooleanField(default=False, verbose_name="다의어"),
                ),
                (
                    "alt_expansions",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="다른 뜻(|구분)"
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[("prefix", "prefix"), ("word", "word")],
                        default="prefix",
                        max_length=10,
                        verbose_name="매칭 방식",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "줄임말 사전",
                "verbose_name_plural": "줄임말 사전",
                "ordering": ["abbr"],
            },
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시각"),
                ),
                ("query", models.TextField(verbose_name="질문")),
                ("normalized", models.TextField(blank=True, verbose_name="정규화")),
                ("grade", models.CharField(max_length=4, verbose_name="등급")),
                (
                    "top1_faq",
                    models.CharField(blank=True, max_length=20, verbose_name="1위 FAQ"),
                ),
                ("top1_score", models.FloatField(default=0, verbose_name="1위 점수")),
                ("gap", models.FloatField(default=0, verbose_name="1·2위 차")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="판정 근거"
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 기록",
                "verbose_name_plural": "질문 기록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faq_id",
                    models.CharField(max_length=20, unique=True, verbose_name="FAQ ID"),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="카테고리"
                    ),
                ),
                (
                    "job_group",
                    models.CharField(blank=True, max_length=60, verbose_name="직무군"),
                ),
                ("rep_question", models.TextField(verbose_name="대표 질문")),
                ("answer", models.TextField(verbose_name="답변")),
                (
                    "discovery_route",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="발굴 경로"
                    ),
                ),
                (
                    "discovery_source",
                    models.TextField(blank=True, verbose_name="질문 출처"),
                ),
                (
                    "evidence_source",
                    models.TextField(blank=True, verbose_name="근거 자료"),
                ),
                (
                    "evidence_summary",
                    models.TextField(blank=True, verbose_name="근거 요약"),
                ),
                (
                    "priority",
                    models.CharField(blank=True, max_length=4, verbose_name="우선순위"),
                ),
                (
                    "checked_date",
                    models.CharField(blank=True, max_length=20, verbose_name="확인일"),
                ),
                (
                    "review_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="검토 상태"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                ("row_no", models.PositiveIntegerField(default=0, verbose_name="순번")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["row_no"],
            },
        ),
        migrations.CreateModel(
            name="Profanity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=40, verbose_name="비속어")),
                ("pattern", models.CharField(max_length=300, verbose_name="정규식")),
                (
                    "type",
                    models.CharField(blank=True, max_length=20, verbose_name="유형"),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(default=1, verbose_name="심각도"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("remove", "제거"), ("mask", "표시만")],
                        default="remove",
                        max_length=10,
                        verbose_name="처리",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "verbose_name": "비속어 사전",
                "verbose_name_plural": "비속어 사전",
                "ordering": ["-severity", "word"],
            },
        ),
        migrations.CreateModel(
            name="Expression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expr_id", models.CharField(max_length=20, unique=True)),
                ("text", models.TextField(verbose_name="표현")),
                (
                    "is_representative",
                    models.BooleanField(default=False, verbose_name="대표 질문"),
                ),
                (
                    "variation_type",
                    models.CharField(blank=True, max_length=30, verbose_name="유형"),
                ),
                (
                    "variation_label",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="유형 설명"
                    ),
                ),
                (
                    "faq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expressions",
                        to="chatbot.faq",
                    ),
                ),
            ],
            options={
                "verbose_name": "검색 표현",
                "verbose_name_plural": "검색 표현",
                "ordering": ["id"],
            },
        ),
    ]
